name: Flutter code analyze CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.9.1
        with:
          channel: stable
          flutter-version: 3.7.12

      - name: Pub Get Packages
        run: flutter pub get

      - name: Analyze Dart
        uses: zgosalvez/github-actions-analyze-dart@v2
